version : '2.2'
services:
  
  app:
    build:
      context: . 
      dockerfile: app.dockerfile
    ports: 
      - "7080"
      - "9991"
      - "9994"
      - "7009"
      - "7443"
      - "13628"
      - "3729"
      - "14712"
      - "14713"
      - "25"
    networks:
      - app-network
    environment:
      - MYSQL_URI=db:3306
    volumes:
      - .:/vol/development 
    depends_on:
       db:
         condition: service_healthy  
       memcached:  
         condition: service_started
  memcached:
     image: memcached
     ports:
       - "11211"
     restart: always
     networks:
      - app-network     
  db:
    build:
      context: . 
      dockerfile: mysql.dockerfile
    ports:
      - "3306"
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_db_user
      - MYSQL_PASSWORD=app_db_pass
      - MYSQL_ROOT_PASSWORD=app_db_pass
      - MYSQL_ROOT_HOST=%
    command: mysqld --lower_case_table_names=1
    healthcheck:
             test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
             timeout: 20s
             retries: 10
    
networks:
  app-network:
    driver: bridge
